import { TankControls } from "./tank-controls.js?v=20260924-66";
import { TankEngine } from "./tank-engine.js?v=20260925-87";
import { AuthoritativeTankEngine } from "./tank-authoritative-engine.js?v=20260924-82";
import { GameServerClient } from "../../services/game-server.js?v=20260924-62";
import { buildTankMatchPayload,resolveTankWinner } from "./tank-rules.js?v=20260924-62";

export const TankGameManifest={id:"tank",name:"Tank Battle 1v1",description:"Confronto direto de tanques em tempo real.",version:"2.2.0",mode:"multiplayer_1v1",rules:{duration_options_seconds:[120,300,600],countdown_seconds:3,win_criteria:["kills"],authority:"server"}};

export const tankGame={
 id:"tank",name:"Tank Battle 1v1",description:"Confronto direto de tanques em tempo real. O servidor é a autoridade da partida.",
 rules:["Explore a arena gigante, colete suprimentos e ganhe créditos por abate.","Evolua onze habilidades em até cinco níveis durante a batalha.","Use o minimapa, ricochetes e melhorias criativas para dominar a arena."],
 multiplayer:{enabled:true,durationMs:120000,countdownMs:3000,scoring:"kills",resolveWinner:resolveTankWinner},
 async create({root,close,options={}}){
  root.innerHTML=`<section class="tank-screen"><header class="module-header tank-header"><button type="button" data-close>←</button><button type="button" class="tank-fullscreen" data-fullscreen aria-label="Tela cheia" title="Tela cheia">⛶</button><div class="tank-score tank-score--a"><small>JOGADOR 1</small><strong data-score-a>0</strong></div><button class="tank-wallet" type="button" data-shop><small>OFICINA</small><strong>◆ <span data-coins>0</span></strong></button><div class="tank-time"><small>TEMPO</small><strong data-clock>02:00</strong></div><div class="tank-ammo" data-ammo><small>MUNIÇÃO</small><strong>6/6</strong></div><div class="tank-score tank-score--b"><small data-opponent-label>JOGADOR 2</small><strong data-score-b>0</strong></div></header><div class="tank-arena"><canvas></canvas><div class="tank-controls-layer"></div><div class="tank-commands"><span><kbd>Q</kbd> BOMBA</span><span><kbd>E</kbd> PULSO</span><span><kbd>SHIFT</kbd> IMPULSO</span><span><kbd>ESPAÇO</kbd> ATIRAR</span></div><div class="tank-countdown">CONECTANDO…</div><aside class="tank-shop" data-shop-panel hidden><header><div><small>OFICINA MK II</small><strong>Árvore de habilidades</strong></div><button type="button" data-shop-close aria-label="Fechar oficina">×</button></header><p>◆ amarelo concede créditos; + verde recupera vida. Ativos: Bomba Nova <b>[Q]</b>, Pulso <b>[E]</b> e Turbo <b>[Shift]</b>.</p><div data-skill-list></div></aside></div></section>`;
  const canvas=root.querySelector("canvas"),layer=root.querySelector(".tank-controls-layer"),countdown=root.querySelector(".tank-countdown"),clock=root.querySelector("[data-clock]"),scoreA=root.querySelector("[data-score-a]"),scoreB=root.querySelector("[data-score-b]"),coins=root.querySelector("[data-coins]"),shop=root.querySelector("[data-shop-panel]"),skillList=root.querySelector("[data-skill-list]"),ammo=root.querySelector("[data-ammo]"),opponentLabel=root.querySelector("[data-opponent-label]");
  const casual=options.mode!=="1v1",difficulty=["basic","hard","pro"].includes(options.difficulty)?options.difficulty:"basic",difficultyLabel={basic:"BÁSICO",hard:"HARD",pro:"PRO"}[difficulty],durationMs=[120000,300000,600000].includes(options.durationMs)?options.durationMs:120000,ctx={...(options.matchContext||options),casual,difficulty,durationMs};ctx.slot=options.slot||ctx.slot;if(casual)opponentLabel.textContent=`MÁQUINA • ${difficultyLabel}`;
  const controls=new TankControls(canvas,layer);let engine,network=null,timer=null,ended=false,startedAt=null;
  if(casual)engine=new TankEngine({canvas,controls,realtimeClient:null,eventBus:options.eventBus,matchContext:ctx});
  else{network=new GameServerClient({roomId:options.roomId||ctx.roomId,playerId:ctx.playerId,desiredDurationMs:options.durationMs});const configPromise=new Promise((resolve,reject)=>{const off=network.on("game_config",cfg=>{off();resolve(cfg)});setTimeout(()=>{off();reject(new Error("GAME_CONFIG_TIMEOUT"))},8000)});await network.connect();const serverConfig=await configPromise;engine=new AuthoritativeTankEngine({canvas,controls,network,playerId:ctx.playerId,config:serverConfig});ctx.serverConfig=serverConfig;}
  const updateHud=()=>{const localIsA=ctx.slot!=="B";scoreA.textContent=localIsA?engine.local.kills:engine.remote.kills;scoreB.textContent=localIsA?engine.remote.kills:engine.local.kills;coins.textContent=engine.local.coins||0;const combat=engine.getCombatState?.();if(ammo&&combat){ammo.querySelector("strong").textContent=combat.reloading?`RECARREGANDO ${(combat.reloadMs/1000).toFixed(1)}s`:`${combat.ammo}/${combat.maxAmmo}`;ammo.classList.toggle("is-reloading",combat.reloading);}if(startedAt){const total=casual?durationMs:(ctx.serverConfig?.durationSeconds||90)*1000,left=Math.max(0,Math.ceil((total-(Date.now()-startedAt))/1000));clock.textContent=`${String(Math.floor(left/60)).padStart(2,"0")}:${String(left%60).padStart(2,"0")}`;}};
  const renderShop=()=>{skillList.innerHTML=engine.getShopState().map(s=>`<button type="button" class="tank-skill" data-skill="${s.id}" ${s.level>=s.max?"disabled":""}><span><b>${s.name}</b><small>${s.description}</small></span><span><em>NÍVEL ${s.level}/${s.max}</em><strong>${s.level>=s.max?"MÁXIMO":`◆ ${s.cost}`}</strong></span></button>`).join("");skillList.querySelectorAll("[data-skill]").forEach(button=>button.onclick=()=>{const result=engine.buySkill(button.dataset.skill);if(!result.ok){button.classList.add("is-denied");setTimeout(()=>button.classList.remove("is-denied"),350);}updateHud();if(!result.pending)renderShop();});};
  root.querySelector("[data-shop]").onclick=()=>{renderShop();shop.hidden=!shop.hidden;};root.querySelector("[data-shop-close]").onclick=()=>shop.hidden=true;const screen=root.querySelector(".tank-screen"),fullBtn=root.querySelector("[data-fullscreen]");const syncFullscreen=()=>{const active=document.fullscreenElement===screen;fullBtn.textContent=active?"⛶":"⛶";fullBtn.title=active?"Sair da tela cheia":"Tela cheia";fullBtn.setAttribute("aria-label",fullBtn.title);screen.classList.toggle("is-fullscreen",active);};fullBtn.onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await screen.requestFullscreen();}catch{}syncFullscreen();};document.addEventListener("fullscreenchange",syncFullscreen);
  const showResult=async payload=>{if(ended)return;ended=true;clearInterval(timer);engine.stop?.();const mine=ctx.playerId,title=!payload.winnerPlayerId?"EMPATE":payload.winnerPlayerId===mine?"VITÓRIA!":"DERROTA";if(window.Swal)await Swal.fire({title,text:`${engine.local.kills} × ${engine.remote.kills} • resultado validado pelo servidor`,icon:title==="VITÓRIA!"?"success":"info",confirmButtonText:"Voltar ao lobby",background:"#11162c",color:"#fff",confirmButtonColor:"#5153e6"});close();};
  if(casual){const startAt=Date.now()+1200;clock.textContent=`${String(durationMs/60000).padStart(2,"0")}:00`;const begin=()=>{const left=startAt-Date.now();if(left>0){countdown.textContent=Math.max(1,Math.ceil(left/1000));setTimeout(begin,Math.min(250,left));return;}countdown.hidden=true;controls.start();engine.start();startedAt=Date.now();timer=setInterval(async()=>{updateHud();if(Date.now()-startedAt>=durationMs){ended=true;clearInterval(timer);engine.stop();const payload=buildTankMatchPayload(engine.local,startedAt,durationMs),won=engine.local.kills>engine.remote.kills;if(window.Swal){const r=await Swal.fire({title:won?"VITÓRIA!":engine.local.kills===engine.remote.kills?"EMPATE":"FIM DE TREINO",text:`${engine.local.kills} × ${engine.remote.kills} • ◆ ${engine.local.coins} • ${payload.metrics.damage_dealt} de dano`,icon:won?"success":"info",showCancelButton:true,confirmButtonText:"Jogar novamente",cancelButtonText:"Voltar aos jogos",background:"#11162c",color:"#fff"});close();if(r.isConfirmed)setTimeout(()=>options.replay?.(),0);}else close();}},250);};begin();}
  else{
   const onCountdown=p=>{countdown.hidden=false;countdown.textContent=p.seconds;};
   const onStart=p=>{countdown.hidden=true;startedAt=p.startedAt||Date.now();controls.start();engine.start();timer=setInterval(updateHud,100);};
   network.on("match_countdown",onCountdown);network.on("match_start",onStart);engine.onFinished=showResult;
   engine.onOpponentDisconnected=()=>{if(window.Swal)Swal.fire({title:"Oponente desconectado",text:"Aguardando reconexão…",icon:"warning",showConfirmButton:false,timer:15000,timerProgressBar:true,background:"#11162c",color:"#fff"});};
   engine.onOpponentReconnected=()=>window.Swal?.close();
  }
  root.querySelector("[data-close]").onclick=async()=>{if(!casual){const r=window.Swal?await Swal.fire({title:"Sair da partida?",text:"A desconexão inicia o período de reconexão; se você não voltar, o servidor aplica a derrota por abandono.",icon:"warning",showCancelButton:true,confirmButtonText:"Sair",cancelButtonText:"Continuar",background:"#11162c",color:"#fff"}):{isConfirmed:confirm("Deseja sair?")};if(!r.isConfirmed)return;}close();};
  return{start(){},destroy(){ended=true;clearInterval(timer);document.removeEventListener("fullscreenchange",syncFullscreen);if(document.fullscreenElement===screen)document.exitFullscreen().catch(()=>{});controls.destroy();engine?.destroy?.();network?.close?.();}};
 }
};
export function init(containerElement,eventBus,realtimeClient,matchContext={}){return tankGame.create({root:containerElement,close:()=>{},options:{eventBus,matchContext,...matchContext}})}
export { buildTankMatchPayload };
