const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));const lerp=(a,b,t)=>a+(b-a)*t;
export class TankEngine{
 #canvas;#ctx;#controls;#net;#bus;#ctxMatch;#raf=0;#sync=0;#running=false;#last=0;#clean=[];#projectiles=[];#tick=0;#w=900;#h=560;
 local={x:120,y:280,bodyAngle:0,turretAngle:0,hp:100,kills:0,totalDamage:0,totalShots:0,hits:0};
 remote={x:780,y:280,targetX:780,targetY:280,bodyAngle:Math.PI,targetBodyAngle:Math.PI,turretAngle:Math.PI,targetTurretAngle:Math.PI,hp:100};
 constructor({canvas,controls,realtimeClient,eventBus,matchContext}){this.#canvas=canvas;this.#ctx=canvas.getContext("2d");this.#controls=controls;this.#net=realtimeClient;this.#bus=eventBus;this.#ctxMatch=matchContext||{};}
 start(){this.#running=true;this.#resize();addEventListener("resize",this.#resizeBound);this.#subscribe();this.#last=performance.now();this.#raf=requestAnimationFrame(this.#loop);this.#sync=setInterval(()=>this.#send("TANK_SYNC",{tick:++this.#tick,x:this.local.x,y:this.local.y,bodyAngle:this.local.bodyAngle,turretAngle:this.local.turretAngle,hp:this.local.hp}),50);}
 #resizeBound=()=>this.#resize();#loop=t=>{if(!this.#running)return;const dt=Math.min(.033,(t-this.#last)/1000);this.#last=t;this.#update(dt);this.#draw();this.#raf=requestAnimationFrame(this.#loop)};
 #resize(){const r=this.#canvas.parentElement.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);this.#canvas.style.width=r.width+"px";this.#canvas.style.height=Math.min(r.width*.64,560)+"px";this.#canvas.width=Math.round(r.width*d);this.#canvas.height=Math.round(Math.min(r.width*.64,560)*d);this.#ctx.setTransform(this.#canvas.width/r.width,0,0,this.#canvas.width/r.width,0,0);}
 #update(dt){const i=this.#controls.getInputs();this.local.bodyAngle+=i.turnSpeed*2.4*dt;this.local.x=clamp(this.local.x+Math.cos(this.local.bodyAngle)*i.moveSpeed*170*dt,28,this.#w-28);this.local.y=clamp(this.local.y+Math.sin(this.local.bodyAngle)*i.moveSpeed*170*dt,28,this.#h-28);this.local.turretAngle=i.turretAngle;if(i.isShooting)this.#shoot();this.remote.x=lerp(this.remote.x,this.remote.targetX,.18);this.remote.y=lerp(this.remote.y,this.remote.targetY,.18);this.remote.bodyAngle=lerp(this.remote.bodyAngle,this.remote.targetBodyAngle,.18);this.remote.turretAngle=lerp(this.remote.turretAngle,this.remote.targetTurretAngle,.18);for(const p of this.#projectiles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.ttl-=dt;if(p.enemy&&Math.hypot(p.x-this.local.x,p.y-this.local.y)<25){p.ttl=0;this.local.hp=Math.max(0,this.local.hp-25);navigator.vibrate?.(100);this.#send("TANK_TAKE_DAMAGE",{hp:this.local.hp,shooter:p.ownerId});if(!this.local.hp)this.#respawn();}}this.#projectiles=this.#projectiles.filter(p=>p.ttl>0&&p.x>0&&p.y>0&&p.x<this.#w&&p.y<this.#h);}
 #shoot(){const now=performance.now();if(now-(this.lastShot||0)<350)return;this.lastShot=now;this.local.totalShots++;const a=this.local.turretAngle,p={id:crypto.randomUUID(),ownerId:this.#ctxMatch.playerId||"local",x:this.local.x,y:this.local.y,vx:Math.cos(a)*420,vy:Math.sin(a)*420,ttl:2,enemy:false};this.#projectiles.push(p);this.#send("TANK_SHOOT",{id:p.id,x:p.x,y:p.y,angle:a,ownerId:p.ownerId});}
 #respawn(){this.#send("TANK_DEAD",{});setTimeout(()=>{this.local.hp=100;this.local.x=120;this.local.y=280},2000)}
 #subscribe(){const handler=m=>{if(!m||m.sender===this.#ctxMatch.playerId)return;if(m.event==="TANK_SYNC"){Object.assign(this.remote,{targetX:m.x,targetY:m.y,targetBodyAngle:m.bodyAngle,targetTurretAngle:m.turretAngle,hp:m.hp})}else if(m.event==="TANK_SHOOT")this.#projectiles.push({id:m.id,ownerId:m.ownerId,x:m.x,y:m.y,vx:Math.cos(m.angle)*420,vy:Math.sin(m.angle)*420,ttl:2,enemy:true});else if(m.event==="TANK_TAKE_DAMAGE"){this.local.totalDamage+=25;this.local.hits++;}else if(m.event==="TANK_DEAD")this.local.kills++};this.#net?.on?.("message",handler);this.#clean.push(()=>this.#net?.off?.("message",handler));}
 #send(event,data){this.#net?.send?.({event,...data,sender:this.#ctxMatch.playerId,matchId:this.#ctxMatch.matchId})}
 #draw(){const c=this.#ctx,sx=this.#canvas.clientWidth/this.#w,sy=this.#canvas.clientHeight/this.#h;c.save();c.scale(sx,sy);c.clearRect(0,0,this.#w,this.#h);c.fillStyle="#080b17";c.fillRect(0,0,this.#w,this.#h);c.strokeStyle="#272d54";c.lineWidth=4;c.strokeRect(2,2,this.#w-4,this.#h-4);this.#tank(c,this.remote,"#ff49c7");this.#tank(c,this.local,"#52ffd2");for(const p of this.#projectiles){c.fillStyle="#fff";c.beginPath();c.arc(p.x,p.y,5,0,Math.PI*2);c.fill()}c.fillStyle="#fff";c.font="700 18px sans-serif";c.fillText(`HP ${this.local.hp}  KILLS ${this.local.kills}`,20,30);c.restore();}
 #tank(c,t,color){c.save();c.translate(t.x,t.y);c.rotate(t.bodyAngle);c.fillStyle=color;c.fillRect(-22,-15,44,30);c.restore();c.save();c.translate(t.x,t.y);c.rotate(t.turretAngle);c.strokeStyle="#fff";c.lineWidth=7;c.beginPath();c.moveTo(0,0);c.lineTo(32,0);c.stroke();c.fillStyle=color;c.beginPath();c.arc(0,0,12,0,Math.PI*2);c.fill();c.restore();}
 destroy(){this.#running=false;cancelAnimationFrame(this.#raf);clearInterval(this.#sync);removeEventListener("resize",this.#resizeBound);this.#clean.splice(0).forEach(f=>f());}
}