export class AuthScreen{
 #auth;#node;#onReady;#onClose;
 constructor({auth,onReady,onClose}){this.#auth=auth;this.#onReady=onReady;this.#onClose=onClose;this.#node=document.createElement("section");this.#node.className="auth-screen";this.#node.hidden=true;document.body.append(this.#node);}
 async boot(){return this.#auth.current()}
 show(){this.#node.hidden=false;document.body.classList.add("auth-open");this.#render("login");}
 hide(){this.#node.hidden=true;document.body.classList.remove("auth-open");}
 close(){this.hide();this.#onClose?.();}
 #render(mode){const signup=mode==="signup";this.#node.innerHTML=`<div class="auth-card"><button class="auth-close" type="button" aria-label="Fechar">×</button><small>DIAMOND GAME</small><h1>${signup?"Criar conta":"Entrar"}</h1><p>${signup?"Crie seu perfil de jogador.":"Entre para jogar partidas 1v1."}</p><form><input name="name" placeholder="Nome de jogador" ${signup?"":"hidden"}><input name="email" type="email" autocomplete="email" placeholder="E-mail" required><input name="password" type="password" autocomplete="${signup?"new-password":"current-password"}" minlength="8" placeholder="Senha" required>${signup?`<label style="display:flex;gap:10px;align-items:flex-start;text-align:left;font-size:12px;line-height:1.4;color:#c8cce2;margin:10px 0"><input name="legal_accept" type="checkbox" required style="width:auto;margin-top:2px"> <span>Li e aceito os <a href="./legal.html#termos" target="_blank" rel="noopener">Termos de Uso</a> e a <a href="./legal.html#privacidade" target="_blank" rel="noopener">Política de Privacidade</a>.</span></label>`:""}<button>${signup?"Criar conta":"Entrar"}</button><div class="auth-error" aria-live="polite"></div></form><button class="auth-switch">${signup?"Já tenho conta":"Criar minha conta"}</button></div>`;
 this.#node.querySelector(".auth-close").onclick=()=>this.close();
 this.#node.querySelector(".auth-switch").onclick=()=>this.#render(signup?"login":"signup");
 this.#node.querySelector("form").onsubmit=async e=>{e.preventDefault();const b=e.currentTarget.querySelector("button"),err=this.#node.querySelector(".auth-error"),data=Object.fromEntries(new FormData(e.currentTarget));b.disabled=true;err.textContent="";try{const user=signup?await this.#auth.signUp(data):await this.#auth.signIn(data);this.hide();this.#onReady(user)}catch(x){err.textContent=this.#message(x)}finally{b.disabled=false}};
 }
 #message(error){const msg=String(error?.message||"");if(/network|fetch/i.test(msg))return "Não foi possível conectar ao servidor. Verifique sua internet e tente novamente.";if(/already|exists/i.test(msg))return "Este e-mail já possui uma conta.";if(/credentials|password|email/i.test(msg))return "E-mail ou senha inválidos.";return msg||"Não foi possível autenticar.";}
}