const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export class BotNavigation{
 #world;#obstacles;#cell;#grid=null;#cache=new Map();targetCell="";
 constructor({width,height,obstacles,cell=72}){this.#world={width,height};this.#obstacles=obstacles;this.#cell=cell;}
 build(){const cell=this.#cell,cols=Math.ceil(this.#world.width/cell),rows=Math.ceil(this.#world.height/cell),grid=Array.from({length:rows},()=>Array(cols).fill(0));for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){const px=x*cell+cell/2,py=y*cell+cell/2;if(px<34||py<34||px>this.#world.width-34||py>this.#world.height-34||this.#obstacles.some(o=>px+32>o.x&&px-32<o.x+o.w&&py+32>o.y&&py-32<o.y+o.h))grid[y][x]=1;}this.#grid={grid,cols,rows};}
 trackTarget(x,y){const next=`${Math.floor(x/this.#cell)}:${Math.floor(y/this.#cell)}`;if(next!==this.targetCell){this.targetCell=next;this.#cache.clear();}}
 blocked(x,y,p=30){return x<p||y<p||x>this.#world.width-p||y>this.#world.height-p||this.#obstacles.some(o=>x+p>o.x&&x-p<o.x+o.w&&y+p>o.y&&y-p<o.y+o.h);}
 lineClear(ax,ay,bx,by){const d=Math.hypot(bx-ax,by-ay),steps=Math.max(2,Math.ceil(d/24));for(let n=1;n<steps;n++){const t=n/steps;if(this.blocked(ax+(bx-ax)*t,ay+(by-ay)*t,18))return false;}return true;}
 path(sx,sy,tx,ty){if(!this.#grid)this.build();const cacheKey=`${Math.floor(sx/this.#cell)}:${Math.floor(sy/this.#cell)}>${this.targetCell}`;if(this.#cache.has(cacheKey))return this.#cache.get(cacheKey).map(p=>({...p}));const {grid,cols,rows}=this.#grid,cell=this.#cell,key=(x,y)=>y*cols+x,toCell=(x,y)=>[clamp(Math.floor(x/cell),0,cols-1),clamp(Math.floor(y/cell),0,rows-1)],nearest=([gx,gy])=>{if(!grid[gy][gx])return[gx,gy];for(let r=1;r<6;r++)for(let y=Math.max(0,gy-r);y<=Math.min(rows-1,gy+r);y++)for(let x=Math.max(0,gx-r);x<=Math.min(cols-1,gx+r);x++)if(!grid[y][x])return[x,y];return[gx,gy];},s=nearest(toCell(sx,sy)),g=nearest(toCell(tx,ty)),open=[{x:s[0],y:s[1],g:0,f:0}],came=new Map(),cost=new Map([[key(s[0],s[1]),0]]),dirs=[[1,0],[-1,0],[0,1],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]];let end=null,guard=0;while(open.length&&guard++<1200){open.sort((a,b)=>a.f-b.f);const cur=open.shift();if(cur.x===g[0]&&cur.y===g[1]){end=cur;break;}for(const [dx,dy] of dirs){const nx=cur.x+dx,ny=cur.y+dy;if(nx<0||ny<0||nx>=cols||ny>=rows||grid[ny][nx])continue;if(dx&&dy&&(grid[cur.y][nx]||grid[ny][cur.x]))continue;const ng=cur.g+(dx&&dy?1.414:1),nk=key(nx,ny);if(ng>=(cost.get(nk)??Infinity))continue;cost.set(nk,ng);came.set(nk,[cur.x,cur.y]);open.push({x:nx,y:ny,g:ng,f:ng+Math.hypot(g[0]-nx,g[1]-ny)});}}if(!end)return[];const result=[];let cur=[end.x,end.y];while(cur[0]!==s[0]||cur[1]!==s[1]){result.push({x:cur[0]*cell+cell/2,y:cur[1]*cell+cell/2});cur=came.get(key(cur[0],cur[1]));if(!cur)break;}result.reverse();const path=result.filter((_,i)=>i===result.length-1||i%2===1);this.#cache.set(cacheKey,path.map(p=>({...p})));return path;}
 reset(){this.#cache.clear();this.#grid=null;this.targetCell="";}
}
